# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Laurent HÃ©bert-Dufresne
email: laurent.hebert.dufresne@gmail.com
description: James S. McDonnell Postdoctoral Fellow at the Santa Fe Institute
url: "http://laurenthebertdufresne.github.io" # the base hostname & protocol for your site
twitter_username: lecomptedelhd
scholar_username: LdkfcuwAAAAJ
#linkedin_username: lecomptedelhd
#github_username: lecomptedelhd

include: ['_pages']
exclude: ['bower_components']

# Build settings
markdown: kramdown

paginate: 5
paginate_path: "/blog/page:num/"

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
